@extends('layouts.app')
@section('title', 'Contract Payroll — ' . ($record->worker->name ?? ''))
@section('page-title', 'Contract Payroll Detail')
@section('page-subtitle', optional($record->worker)->name . ' — ' . \Carbon\Carbon::create($record->year, $record->month)->format('F Y'))

@section('page-actions')
    <a href="{{ route('contract-payroll.index') }}" class="btn btn-outline-secondary btn-sm">
        <i class="bi bi-arrow-left"></i> Payroll List
    </a>
@endsection

@section('content')
<div class="row g-3">

    {{-- Worker & Contractor Info --}}
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-header"><i class="bi bi-person-badge"></i> Worker Details</div>
            <div class="card-body">
                <table class="table table-sm table-borderless mb-0">
                    <tr><td class="text-muted">Worker Name</td><td class="fw-semibold">{{ optional($record->worker)->name }}</td></tr>
                    <tr><td class="text-muted">Contractor</td><td>{{ optional($record->contractor)->name }}</td></tr>
                    <tr><td class="text-muted">Skill Type</td><td>{{ optional($record->worker)->skill_type ?? '—' }}</td></tr>
                    <tr><td class="text-muted">Wage Type</td><td>
                        <span class="badge bg-{{ $record->wage_type === 'daily' ? 'info' : 'primary' }}-subtle text-{{ $record->wage_type === 'daily' ? 'info' : 'primary' }}">
                            {{ ucfirst($record->wage_type) }} Rate
                        </span>
                    </td></tr>
                    <tr><td class="text-muted">Rate</td><td class="fw-semibold">₹{{ number_format($record->wage_amount, 2) }} / {{ $record->wage_type === 'daily' ? 'day' : 'month' }}</td></tr>
                    <tr><td class="text-muted">Period</td><td>{{ \Carbon\Carbon::create($record->year, $record->month)->format('F Y') }}</td></tr>
                    <tr><td class="text-muted">Generated By</td><td>{{ optional($record->generator)->name ?? 'System' }}</td></tr>
                </table>
            </div>
        </div>
    </div>

    {{-- Attendance Summary --}}
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-header"><i class="bi bi-calendar-check"></i> Attendance Summary</div>
            <div class="card-body">
                <div class="row g-2 text-center">
                    <div class="col-4">
                        <div class="p-2 bg-light rounded">
                            <div class="fw-bold fs-4">{{ $record->total_days }}</div>
                            <small class="text-muted">Working Days</small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="p-2 bg-success-subtle rounded">
                            <div class="fw-bold fs-4 text-success">{{ number_format($record->present_days, 1) }}</div>
                            <small class="text-muted">Present</small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="p-2 bg-warning-subtle rounded">
                            <div class="fw-bold fs-4 text-warning">{{ number_format($record->half_days, 1) }}</div>
                            <small class="text-muted">Half Days</small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="p-2 bg-danger-subtle rounded">
                            <div class="fw-bold fs-4 text-danger">{{ number_format($record->absent_days, 1) }}</div>
                            <small class="text-muted">Absent</small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="p-2 bg-info-subtle rounded">
                            <div class="fw-bold fs-4 text-info">{{ number_format($record->ot_hours, 1) }}</div>
                            <small class="text-muted">OT Hours</small>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="p-2 bg-primary-subtle rounded">
                            <div class="fw-bold fs-4 text-primary">
                                {{ number_format($record->present_days + ($record->half_days * 0.5), 1) }}
                            </div>
                            <small class="text-muted">Effective Days</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Wage Calculation --}}
    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><i class="bi bi-cash-stack"></i> Wage Calculation</div>
            <div class="card-body">
                <table class="table table-sm mb-0">
                    <tr>
                        <td>Base Wages</td>
                        <td class="text-end">₹{{ number_format($record->total_wages, 2) }}</td>
                    </tr>
                    <tr>
                        <td>OT Amount</td>
                        <td class="text-end">₹{{ number_format($record->ot_amount, 2) }}</td>
                    </tr>
                    <tr class="table-light">
                        <td class="fw-semibold">Gross Wages</td>
                        <td class="text-end fw-semibold">₹{{ number_format($record->gross_wages, 2) }}</td>
                    </tr>
                    <tr>
                        <td class="text-danger">Deductions</td>
                        <td class="text-end text-danger">— ₹{{ number_format($record->deductions, 2) }}</td>
                    </tr>
                    <tr class="table-success">
                        <td class="fw-bold fs-6">Net Wages</td>
                        <td class="text-end fw-bold fs-6 text-success">₹{{ number_format($record->net_wages, 2) }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    {{-- Payment Status --}}
    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><i class="bi bi-credit-card"></i> Payment Status</div>
            <div class="card-body">
                @php $pc = ['pending'=>'warning','paid'=>'success','cancelled'=>'secondary']; @endphp
                <div class="text-center mb-3">
                    <span class="badge bg-{{ $pc[$record->payment_status] }}-subtle text-{{ $pc[$record->payment_status] }} fs-6 px-4 py-2">
                        {{ ucfirst($record->payment_status) }}
                    </span>
                    @if($record->payment_date)
                        <div class="text-muted small mt-1">Paid on {{ $record->payment_date->format('d M Y') }}</div>
                    @endif
                    @if($record->payment_remarks)
                        <div class="text-muted small">{{ $record->payment_remarks }}</div>
                    @endif
                </div>

                @if($record->payment_status === 'pending')
                    <form action="{{ route('contract-payroll.pay', $record->id) }}" method="POST">
                        @csrf
                        <div class="mb-2">
                            <label class="form-label">Payment Date <span class="text-danger">*</span></label>
                            <input type="date" name="payment_date" class="form-control form-control-sm"
                                   value="{{ now()->toDateString() }}" required>
                        </div>
                        <div class="mb-2">
                            <label class="form-label">Remarks</label>
                            <input type="text" name="payment_remarks" class="form-control form-control-sm" placeholder="Optional">
                        </div>
                        <button type="submit" class="btn btn-success btn-sm w-100">
                            <i class="bi bi-check-circle"></i> Mark as Paid
                        </button>
                    </form>
                @endif
            </div>
        </div>
    </div>

</div>
@endsection
